# Generated by Django 2.2.6 on 2020-04-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Img', models.ImageField(blank=True, default='not found', upload_to='img')),
                ('Enrollment_no', models.TextField(blank=True, default='not found')),
                ('Scholar_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Class', models.TextField()),
                ('Section', models.TextField(blank=True, default='not found')),
                ('Year', models.IntegerField()),
                ('Email', models.EmailField(blank=True, default='not found', max_length=254)),
                ('Father_name', models.CharField(blank=True, default='not found', max_length=50)),
                ('Mother_name', models.CharField(blank=True, default='not found', max_length=50)),
                ('Mobile_no', models.TextField(blank=True, default='not found')),
                ('Address', models.TextField(blank=True, default='not found')),
                ('City', models.TextField(blank=True, default='not found')),
                ('Sem1', models.ImageField(blank=True, default='not found', upload_to='result/sem1')),
                ('Sem2', models.ImageField(blank=True, default='not found', upload_to='result/sem2')),
                ('Sem3', models.ImageField(blank=True, default='not found', upload_to='result/sem3')),
                ('Sem4', models.ImageField(blank=True, default='not found', upload_to='result/sem4')),
            ],
        ),
    ]
