# Generated by Django 2.2.6 on 2020-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='City',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='Enrollment_no',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Father_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='Img',
            field=models.ImageField(blank=True, default='IMG', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Mobile_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='Mother_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='Section',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sem1',
            field=models.ImageField(blank=True, upload_to='result/sem1'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sem2',
            field=models.ImageField(blank=True, upload_to='result/sem2'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sem3',
            field=models.ImageField(blank=True, upload_to='result/sem3'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sem4',
            field=models.ImageField(blank=True, upload_to='result/sem4'),
        ),
    ]
