# Generated by Django 2.2.6 on 2020-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200424_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
