# Generated by Django 2.2.6 on 2020-04-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200424_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Dob',
            field=models.DateField(null=True),
        ),
    ]
